### ISSUE TITLE
Can't reject badge

### ISSUE THREAD

**Issue by h3zjp** [verbiricha/badges#1]
Even if I try to reject a badge that has been "Awarded", I can't reject it because the "Reject" button cannot be pressed.
You can press the "Accept" button.
If I don't want to receive the badge, should I just leave it as is?
Please confirm.

**Comment by verbiricha** [comment]
Yes, just leave it as is. "Reject" should be renamed to "Hide" since what it does is remove it from your "Accepted" list. will add a third option to hide them from award list forever too and improve the wording.

**Comment by h3zjp** [comment]
I've got it!
We are waiting for the change to be reflected 🤩
